-- Create and use database
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'SPMS1')
    CREATE DATABASE SPMS1;
GO
USE SPMS1;
GO

-- Customer table
CREATE TABLE CUSTOMER (
    C_ID INTEGER PRIMARY KEY,
    CNAME VARCHAR(50),
    ADDRESS VARCHAR(75),
    PHONE_NUMBER BIGINT,
    EMAIL VARCHAR(25)
);
GO

-- Vendor table
CREATE TABLE VENDOR (
    VID INT PRIMARY KEY,
    VNAME VARCHAR(50),
    ADDRESS VARCHAR(75),
    PHONE_NUMBER BIGINT,
    EMAIL VARCHAR(25)
);
GO

-- Product table
CREATE TABLE PRODUCT (
    PID INT PRIMARY KEY,
    PNAME VARCHAR(50),
    AMOUNT DECIMAL(12,2),
    VID INT CONSTRAINT FK1 FOREIGN KEY REFERENCES VENDOR(VID) ON DELETE CASCADE
);
GO

-- MyOrder table
CREATE TABLE MYORDER (
    ORD_ID INT PRIMARY KEY,
    PID INT CONSTRAINT FK2 FOREIGN KEY REFERENCES PRODUCT(PID),
    CID INT CONSTRAINT FK3 FOREIGN KEY REFERENCES CUSTOMER(C_ID) ON DELETE CASCADE,
    DATE DATE,
    AMOUNT DECIMAL(12,2)
);
GO

-- Order Details table (fixed cascade conflict)
CREATE TABLE ORDER_DETAILS (
    ORD_ID INT CONSTRAINT F6 FOREIGN KEY REFERENCES MYORDER(ORD_ID) ON DELETE CASCADE,
    PID INT CONSTRAINT F7 FOREIGN KEY REFERENCES PRODUCT(PID),
    QUANTITY INT,
    PRIMARY KEY(PID, ORD_ID)
);
GO

-- Stock table
CREATE TABLE STOCK (
    PID INT CONSTRAINT FK4 FOREIGN KEY REFERENCES PRODUCT(PID) ON DELETE CASCADE,
    QUANTITY INT,
    PRIMARY KEY(PID)
);
GO

-- Login table
CREATE TABLE LOGIN (
    UserName VARCHAR(25),
    Password VARCHAR(20),
    PRIMARY KEY(UserName, Password)
);
GO

-- Insert admin login
INSERT INTO LOGIN VALUES ('admin', 'admin');
GO

-- Create Views
CREATE VIEW ORDER_VIEW AS
SELECT M.ORD_ID, C.C_ID, C.CNAME, C.ADDRESS, C.PHONE_NUMBER, C.EMAIL,
       D.PID, P.PNAME, D.QUANTITY, M.AMOUNT, M.DATE
FROM MYORDER M
JOIN ORDER_DETAILS D ON M.ORD_ID = D.ORD_ID
JOIN CUSTOMER C ON M.CID = C.C_ID
JOIN PRODUCT P ON P.PID = D.PID;
GO

CREATE VIEW CURRENTLY_AVAILABLE_STOCK AS
SELECT P.PID, P.PNAME, P.AMOUNT, S.QUANTITY
FROM PRODUCT P
JOIN STOCK S ON P.PID = S.PID;
GO

CREATE VIEW PRODUCT_VIEW AS
SELECT P.PID, P.PNAME, P.AMOUNT, P.VID, V.VNAME
FROM PRODUCT P
JOIN VENDOR V ON P.VID = V.VID;
GO

-- Create Stored Procedure
CREATE PROCEDURE customer_in
    @cid INT,
    @cname VARCHAR(50),
    @address VARCHAR(75),
    @phone_number BIGINT,
    @email VARCHAR(25)
AS
    INSERT INTO CUSTOMER VALUES(@cid, @cname, @address, @phone_number, @email);
GO

-- Verify data
SELECT * FROM LOGIN;
SELECT * FROM CUSTOMER;
SELECT * FROM MYORDER;
SELECT * FROM ORDER_DETAILS;
GO